.github/workflows/ci.yml
src/app.rs
src/systems.rs

Add basic CI/CD

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
README.md
examples/basic.rs

Plugin compliance

---

examples/basic.rs
src/systems.rs
src/tile_makers.rs

#6 
This addresses layer offsets and also partially addresses strange tileset grid sizes. For the latter, the results don't look exactly like they do in LDTK, but they are at least reasonable.

Layer offsets

---

examples/basic.rs
examples/derive.rs
src/app.rs
src/systems.rs
src/tile_makers.rs
src/utils.rs

Registration defaulting + Layer selection

---

Cargo.lock
Cargo.toml
examples/basic.rs
examples/derive.rs
examples/platformer/main.rs
macros/src/ldtk_entity.rs
src/app/ldtk_entity.rs
src/app/ldtk_int_cell.rs
src/app/mod.rs
src/app/register_ldtk_objects.rs
src/assets.rs
src/systems.rs

New renderer

---

src/utils.rs

Entity tileset scaling

---

src/systems.rs
src/utils.rs

Transform helpers

---

examples/basic.rs
examples/platformer/main.rs
macros/src/ldtk_entity.rs
macros/src/ldtk_int_cell.rs
src/app/ldtk_entity.rs
src/app/ldtk_int_cell.rs
src/app/register_ldtk_objects.rs
src/lib.rs
src/systems.rs

Ldtk objects

---

src/app/mod.rs
src/components.rs
src/ldtk/mod.rs
src/lib.rs
src/systems.rs

Labels and stages

---

examples/platformer/main.rs
src/ldtk/mod.rs
src/tile_makers.rs
src/utils.rs

Use Vec2 and IVec2 in ldtk types

---

macros/README.md
macros/src/ldtk_entity.rs
macros/src/ldtk_int_cell.rs

Generic bundles

---

examples/platformer/components.rs
examples/platformer/main.rs
examples/platformer/systems.rs
macros/src/ldtk_entity.rs
macros/src/lib.rs
src/app/ldtk_entity.rs
src/components.rs
src/lib.rs
src/systems.rs
src/tile_makers.rs
src/utils.rs

Grid coords

---

macros/src/ldtk_entity.rs
src/app/ldtk_entity.rs
src/components.rs
src/tile_makers.rs
src/utils.rs

Ldtk entity constructors

---

src/systems.rs
src/tile_makers.rs

Bug fix: Int grid invisible auto tiles

---

examples/platformer/components.rs
examples/platformer/main.rs
examples/platformer/systems.rs

Enrich the platformer example to show how Entity Instance can be initiated and retrieved in a system.

enrich platformer example

---

src/systems.rs
src/tile_makers.rs

Layer opacity

---

src/components.rs
src/ldtk/mod.rs
src/level.rs
src/lib.rs

Accidentally started work on this in main w/ these 3 commits, woops: f9be9c70194fb068e9ab9ab35fbfe5bdd520c5d0 8a0b7281a5e9ee6ac4fe01a886975673075fa69c 8539846e82bae985e33a522eb2cd3a1ae8da9889
Closes #97

feat: layer metadata

---

.github/workflows/ci.yml
examples/platformer/systems.rs
src/systems.rs

I also updated the CI to run on pushes to main, since I think this is what the CI badge uses to determine if the CI passes or not (I expected it to be failing after the last PR)

fix: apply clippy fixes

---

Cargo.toml
examples/platformer/systems.rs
macros/src/ldtk_entity.rs
macros/src/ldtk_int_cell.rs
macros/src/lib.rs

Hoping this will allow the release-bot to increment the macros version as well. Though, we may need to be careful about how it's treated as a dependency in the root package...

build: add workspace to Cargo.toml including macros

---

src/lib.rs

Add missing type registrations

---

src/assets.rs
src/ldtk/field_instance.rs
src/ldtk/mod.rs
src/plugin.rs

closed earlier commit and reopened with my main branch and commits
derives Reflect and FromReflect on the necessary parts for LdtkLevel and i added too World too but its not used
mostly just used too visually debug things in egui_inspector, but can be useful elswhere.
i have reflect_ignore on the real_editor_values Vec<serde_json::Value> because its external
i need a git crash course,
i tried too rebase from main but it would then ask me too pull down changes from my fork, i just rebased my branches main kinda on accident but its fixed now

add reflect too LdtkLevel and all parts

---

src/systems.rs

Forgot to run CI on this PR before merging it. This should make the CI happy going forward.

chore: format code after merging #281

---

README.md
src/components/ldtk_sprite_sheet_bundle.rs

Updating the compatibility chart for the new version, and also fixing a doc that I forgot to commit in the previous PR.

chore: prepare 0.10 release

---

Cargo.toml
book/src/explanation/game-logic-integration.md
book/src/how-to-guides/make-level-selection-follow-player.md
book/src/how-to-guides/respawn-levels-and-worlds.md
book/src/tutorials/tile-based-game/add-gameplay-to-your-project.md
examples/collectathon/coin.rs
examples/collectathon/main.rs
examples/collectathon/player.rs
examples/collectathon/respawn.rs
examples/field_instances/level_title.rs
examples/field_instances/main.rs
examples/level_set.rs
examples/platformer/camera.rs
examples/platformer/climbing.rs
examples/platformer/game_flow.rs
examples/platformer/walls.rs
examples/tile_based_game.rs
src/assets/ldtk_json_with_metadata.rs
src/assets/ldtk_project.rs
src/ldtk/impl_definitions.rs
src/plugin.rs
src/systems.rs
src/utils.rs

This is an update to #353 and https://github.com/nfagerlund/bevy_ecs_ldtk/tree/may25-bevy016 with the chhanges needed to update to the published versions.
* I haven't run all the examples and confirmed they still work yet.

update to Bevy 0.16
