- Cargo.lock
- Cargo.toml
- README.md
- src/systems.rs
Using tile spacing doesn't result in a crash thanks to the atlas feature: #54 
Closes #39
> Tile spacing "fix"

- README.md
- src/lib.rs
Adding a link to the README for the LDtk website for people who stumble upon bevy_ecs_ldtk without knowing what LDtk is.
> Added a link to LDtk in README

- src/components.rs
This makes the types easier to work with when serializing save games or implementing network rollback.
With this patch, it works with https://github.com/johanhelsing/bevy_snap
> Add Reflect derives for components

- examples/platformer/components.rs
- examples/platformer/main.rs
- examples/platformer/systems.rs
Restrict jumping to only happening when ground detection through shape casting with a filter says the player is on the ground.
This works for normal platforms. It ignores climbables by filtering them out of the shape cast.
You can still multi-jump up walls with this solution and I'm not sure how to fix that. The multi-jump up walls is caused by the wider shape cast than the character, which results in a nice coyote jump when leaving ledges. Shortening the shape does remove the "multi-wall-jump" effect (and also the coyote effect), so I assume it's because the shape cast is actually *in* the wall.
related to #44
> Implement Ground detection in platformer example

- src/systems.rs
> fix: COPY_SRC no longer added to modified textures

- Cargo.lock
- Cargo.toml
- examples/basic.rs
- macros/src/ldtk_entity.rs
- src/components.rs
- src/level.rs
- src/lib.rs
- src/systems.rs
- src/tile_makers.rs
- src/utils.rs
I moved the Bevy dependency to 0.8 and the bevy_ecs_tilemap one to 0.7, then started looking for whatever broke. 
~This isn't a complete upgrade and it isn't in proper working condition (the examples still need a Heron bump that isn't out yet, and also I'm still trying to untangle whatever's going on with inherited visibility), but it IS building. And all these changes seem to be things you'd have needed to do anyway, so maybe it'll save you a couple steps.~
This _seems_ to be mostly in proper working order at this point, but the examples (except `basic`) still need updates, including a Heron upgrade that I think isn't out yet. There's also some outstanding cleanup that needs done and warnings that need dealt w/, which you probably already knew about.
> A little bit of help on the refactor/tilemap-rewrite branch

- Cargo.toml
- examples/platformer/main.rs
- examples/platformer/systems.rs
- src/components.rs
- src/level.rs
- src/lib.rs
- src/resources.rs
- src/systems.rs
Closes #96
Closes #108
This is a pretty major change internally. If you're reading this and want to help me out, **please** update your games to this branch and let me know here whether or not there are any issues. I would like this to be the final PR before releasing 0.4, and I would like to release 0.4 very soon.
```toml
bevy_ecs_ldtk = { git = "https://github.com/Trouv/bevy_ecs_ldtk", branch = "feat/respawn" }
```
The scheduling has been completely reworked, and some systems have been significantly changed as a result. However, this is definitely an improvement. Many frame-delay issues are addressed by this rework, and hot reloading works again. This change was assisted by a new `Respawn` component, which can work on world entities and level entities. As a bonus, users can use the …
> feat: add `Respawn` component and rework schedule using it

- src/app/ldtk_entity.rs
- src/level.rs
- src/systems.rs
This pull request adds the identifier of levels and of layers to the entities spawned by `bevy_ecs_ldtk`.
This makes it a lot easier to see quickly what's going on in the hierarchy, for example with [bevy-inspector-egui](https://github.com/jakobhellermann/bevy-inspector-egui).
> Insert `Name` component into entities spawned by crate

- src/level.rs
Skip the spawning of the entity and not only of the insertion of the components when an entity is found in the worldly_set. The empty entity doesn't seem to cause any issues, but it also doesn't do anything useful.
> fix: do not spawn empty ECS entity for omitted worldly entities

- macros/src/ldtk_entity.rs
- macros/src/lib.rs
- src/app/ldtk_entity.rs
Adds a new attribute to the `LdtkEntity` derive macro named `with`. It allows for bundles to implement custom initializers using a method. This macro takes in a scoped function with signature `(e: EntityInstance) -> T` where T is the field type.
```rs
pub struct Bundle {
#[with(foo_initializer)]
foo: i32;
}
fn foo_initializer(_e: EntityInstance) -> i32 {
4
}
```
<details>
<summary>Longer Example</summary>
```rs
#[derive(Clone, Default, Bundle)]
pub struct ColliderBundle {
pub collider: Collider,
pub rigid_body: RigidBody,
pub damping: Damping,
...
}
#[derive(Bundle, Default, LdtkEntity)]
pub struct PlayerBundle {
player: Player,
#[with(player_collider)]
#[bundle]
collider: ColliderBundle,
}
fn player_collider(_: EntityInstance) -> ColliderBundle {
ColliderBundle {
collider: …
```
> With attribute

- src/level.rs
> fix: filter out tiles that are out of the level's bounds (due to rectangle of tiles rules)

- Cargo.lock
- Cargo.toml
- examples/platformer/components.rs
- examples/platformer/main.rs
- examples/platformer/systems.rs
The refactor consists of basically two things:
- show use of `bevy_rapier2d` in platformer example
- add `bevy_rapier2d` in cargo file and remove `heron`
For the most part I tried to not change too much of the platformer example. 
There we're some minor things though that came up whith which I had to struggle a bit.
- rename `CollisionShape` -> `Collider`
- rename `Velocity.linear` -> `Velocity.linvel`
- create `SensorBundle` since there is no `RigidBody::Sensor` in `rapier2d`
- set player friction to `0.0` because the collider kept sticking to the wall when moving against it in air
- add `RapierDebugRenderPlugin` to showcase colliders with gizmos
- `pause_physics_during_load` uses RapierConfiguration now
- add `ExternalForce` to `ColliderBundle` for jumps
I noticed that my fix for …
> refactor: move from bevy_heron to bevy_rapier2d

- Cargo.toml
- examples/basic.rs
- examples/field_instances.rs
- examples/level_set.rs
- examples/platformer/main.rs
- examples/platformer/systems.rs
- examples/traitless.rs
- macros/src/ldtk_entity.rs
- src/app/ldtk_entity.rs
- src/app/ldtk_int_cell.rs
- src/level.rs
- src/lib.rs
- src/resources.rs
- src/systems.rs
- src/tile_makers.rs
- src/utils.rs
Does not apply to the platformer example (rapier2d) because we are waiting on https://github.com/dimforge/bevy_rapier/pull/272. When that PR is merged I will update this.
> Migrated to bevy 0.9

- examples/platformer/main.rs
- examples/platformer/systems.rs
The ground detection was checked every tick,
and the collision event system was always iterating the sensor before the collision events. I'm not sure, but it feels like bad practice.
This PR might be just a personal preference. But it feels to me more readable and better practice/performance.
Thank you for the consideration and any response.
PS: I left the DebugRender in, as recently the grid update shifted the colliders (nicely visible with this plugin). I'm sure somebody is already considering a fix for this.
> improve ground detection

- src/app/ldtk_entity.rs
I was wondering whether I hit a bug before I scrolled down and found sprite_sheet_bundle
> docs: Explain that sprite_bundle should not be used with tilemap editor visuals

- src/components.rs
If you want to spawn multiple levels at once and handle loading unloading yourself (not using global resources), it's useful to be able to do things like this:
```rust
commands.spawn(LdtkWorldBundle {
ldtk_handle: asset_server.load("levels.ldtk"),
level_set: LevelSet::from_iid("58e02ac0-5110-11ed-b070-cdccc74eaccd"),
..default()
})
```
> feat: Add LevelSet::from_iid

- src/lib.rs
Types need to be registered for `bevy-inspector-egui` (and other tools) to know about them. Do it in the plugin so it's convenient for users.
> feat: Register types `GridCoords` and `LayerMetadata`

- examples/platformer/components.rs
- macros/src/ldtk_entity.rs
- src/app/ldtk_entity.rs
- src/ldtk/mod.rs
EntityInstance is a rather large struct, and cloning it requires allocating for several fields. Despite this fact, each use of the #[from_entity_instance] attribute was cloning the struct once, wasting CPU time for no good reason - especially for Bundles that contain several #[from_entity_instance] fields.
Change the attribute to work on From<&EntityInstance> instead of From<EntityInstance>, avoiding the implicit clone in most cases. The clone is still necessary when a plain EntityInstance field exists in a struct deriving LdtkEntity, which is handled by having EntityInstance implement From<&EntityInstance>.
While being a breaking change, fixing up users should be trivial - in most cases no owned EntityInstance is needed at all, and where it is an explicit clone can be inserted.
> refactor: change #[from_entity_instance] to use references

- src/app/ldtk_entity.rs
- src/app/ldtk_int_cell.rs
This updates docs to use full paths to external documentation instead of depending on the module's imports. I'm not 100% sure this will work, these links have always worked locally so it's hard to tell what will and won't work on docs.rs. However, I've seen documentation linked like this in `iyes_loopless` [here](https://docs.rs/iyes_loopless/latest/src/iyes_loopless/condition.rs.html#211). In that case, it linked to a bevy subcrate and not a prelude. I could see the indirection of linking to `bevy::prelude` causing problems here too, but I think it's worth a shot.
> docs: repair doc links to bevy in app module

- src/app/ldtk_int_cell.rs
- src/ldtk/mod.rs
- src/lib.rs
- src/utils.rs
> Document feature flags in crate-level docs

- Cargo.toml
- examples/platformer/components.rs
- examples/platformer/main.rs
- examples/platformer/systems.rs
- src/lib.rs
- src/resources.rs
> Update to Bevy `0.10`

- .github/workflows/release-please.yml
The changelog currently only shows breaking changes, features, and bug fixes. In other words, only changes that release-please deems worthy for users to care about. For our purposes, changes to docs and examples are also good for users to know. Furthermore, I'd just like to give credit where credit is due in the changelog, especially for changes to the examples since the platformer example is pretty extensive. 
This PR adds more sections to the changelog - docs, examples, refactors, and CI. The latter two are deemed as "hidden" for now. I'm hoping that the hidden option gives them an expandable section rather than completely hiding them from the changelog, we will see.
> ci: add more changelog sections for release-please to generate

- src/level.rs
Our solution for background colors was pretty bad due to a previous limitation with `bevy`'s sprites. We can now use a normal sprite for the background color instead of a single-tile tilemap. This PR makes that change.
This also unblocks #169, since it seems the z-indexing issue was partially due to our weird use background image solution. Though, I expect bevy_ecs_tilemap to release an `0.11` somewhat soon to make the 3d-iso changes optional.
> fix: use normal sprite for background color instead of tile

- Cargo.toml
- README.md
Getting this up pre-emptively so we can quickly release after `bevy_ecs_tilemap`. This branch will fail to compile until `bevy_ecs_tilemap` 0.10 is released. If you want to preview the upgrade to bevy 0.10 in your own game, you can point to the main branch of this repo and use the patch removed in this diff in your dependencies:
```
bevy_ecs_ldtk = { git = "https://github.com/Trouv/bevy_ecs_ldtk", branch = "main" }
[patch.crates-io]
bevy_ecs_tilemap = { git = "https://github.com/geieredgar/bevy_ecs_tilemap", branch = "bevy_track" }
```
> chore: prepare 0.6 release

- src/lib.rs
- src/plugin.rs
This minor change helps clean up the root `lib.rs` file. No import paths have been changed, so this is not a breaking change for users.
> refactor: move plugin module to its own file

- Cargo.toml
- examples/platformer/components.rs
- src/ldtk/all_some_iter.rs
- src/ldtk/ldtk_fields.rs
- src/ldtk/mod.rs
- src/lib.rs
Closes #175.
Users have predictable LDtk entities and know the exact nature of any ldtk field they've created: its identifier, its type, and whether or not it's nullable. However, finding an instance and coercing it to the type the user *knows* it should be involves a lot of boilerplate with several layers of `.iter().find(...)`s, `match`es, `if let`s and `.unwrap()`s.
This PR adds many extension methods to `Level` and `EntityInstance` to take that burden from the user. For every variant of `FieldValue`, this adds a method (or two) for accessing a field instance at a given identifier with that type - unwrapping the variant to its internal type. For example, there is a `.get_maybe_int_field("MyIdentifier")` which, if the field instance exists and is an `Int`, will return an `&Option<i32>` …
> feat: add LdtkFields trait with convenience methods for accessing field instances

- src/assets.rs
- src/ldtk/mod.rs
- src/level.rs
- src/systems.rs
Closes #172, and resolves an issue brought up by @Mattincho in #176 
The white image generated for levels is now only used for intgrid coloring. This means it no longer needs to be the size of the level - it can just be the size of the maximum-sized intgrid layer. The maximum-sized intgrid tile is easy to determine during asset loading. This PR creates a small white-image for the maximum-sized intgrid tile once for the entire asset, rather than a large one once per level. This should improve performance, and also hopefully resolve issues with hitting hardware limits on larger levels.
BREAKING CHANGE: Most likely won't affect users - `LdtkAsset` has gained a `int_grid_image_handle` field, breaking any manual construction of it.
> fix!: create IntGrid white-image on asset load and minimize its size

- src/level.rs
Currently, if a user provides a custom constructor for `Name` via `LdtkEntity` registration, it will be overwritten by the plugin since it automatically inserts a name from the ldtk entity identifier. This change performs this insertion *before* evaluating `LdtkEntity` so that a user-provided `Name` will overwrite the plugin-provided `Name` instead.
> fix: insert Name component before evaluating `LdtkEntity`

- examples/field_instances/enemy.rs
- examples/field_instances/main.rs
- examples/field_instances/mother.rs
- src/components.rs
- src/components/entity_iid.rs
- src/components/mod.rs
- src/level.rs
- src/lib.rs
- src/plugin.rs
This is a first step on the road to having an easy way of looking up entity information from `LdtkAsset`.
**Questions**
* ~~Should it be possible to disable this using `LdtkSettings`? I'm not sure it's worth worrying about as the memory usage should be minimal as the IID are always GUIDs. Perhaps a feature?~~
* ~~Should this be a newtype? It makes sense to me and I can't see any reason for it to ever gain fields, but the other components within the crate all have named fields.~~
* ~~Should the `EntityIid` also carry its `Handle<LdtkAsset>`? I don’t think so personally as `LevelSelection` doesn’t have this concept.~~
> feat: add `EntityIid` component which is added to all entities by default

- examples/level_set.rs
- src/assets.rs
- src/systems.rs
The y-values used for spawning levels in the `UseWorldTranslation` case were incorrect. There were a couple problems:
- the world translation in LDtk was treated as relative to the height of the world, when it was actually relative to the origin
- the method for getting the world height `LdtkAsset::world_height` was incorrect, instead calculating more of a "world depth"
BREAKING-CHANGE: `LdtkAsset::world_height` has been removed
> fix!: remove `LdtkAsset::world_height` and correct `UseWorldTranslation` y-calculation

- .github/workflows/lint.yml
- src/tile_makers.rs
This changes the linting CI drastically to be based off the most recent [`bevy_github_ci_template`](https://github.com/bevyengine/bevy_github_ci_template/blob/1b5cf1bc15ef33cc76eb2e7ef1d6150504ed8687/.github/workflows/ci.yaml). This upgrade includes switching to the actively-maintained dtolnay actions, and implements caching.
This template was updated to have all jobs run against all-targets and all-features as necessary. This begins to resolve a couple of code-review pain-points for me, like having to lint the examples/tests myself.
The template was also updated to have a `check` job. I imagine this was excluded from the template since checking compilation is implicitly performed by the test job. However, I think it's a good idea to include some basic checks that various feature …
> ci: upgrade CI to current bevy_github_ci_template and lint more targets/features

- src/components/entity_iid.rs
These code links were broken since the code they point to isn't imported. This caused warnings when building the documentation.
> docs: fix code links in entity_iid module

- README.md
Adds a new `main` line which copies the current compatibility, and updates the previous compatibility to `bevy_ecs_ldtk` 0.8. Would love to automate this with release-please at some point, but it doesn't seem like it'll be very easy unfortunately.
> chore: update compatibility chart for 0.8 release

- src/ldtk/loaded_level.rs
- src/ldtk/mod.rs
Works towards #205.
In order to better handle internal/external level storage, it will be helpful to a have a type that represents "complete" level data. For projects with internal levels, the normal levels embedded on the LdtkProject are "complete". For external level projects, the levels on the main project file are incomplete, and the complete data is stored separately.
This provides a type for representing complete level data. It does so by wrapping around `Level` by reference, and enforces the loadedness of the borrowed level on construction. It also provides immutable getters for all the level's fields, and `.expects()` away the fields that will not be null since the level is loaded (`layer_instances`).
> feat: add LoadedLevel type that wraps around levels with complete data

- src/assets/level_metadata.rs
- src/assets/level_metadata_accessor.rs
- src/assets/mod.rs
- src/ldtk/raw_level_accessor.rs
- src/lib.rs
Works towards #205.
The asset types are being redesigned a bit to clone less and provide better APIs. One design goal is to correctly handle both external level projects and internal level projects. Since we want to avoid loading level data into a separate asset in the internal level case, these two scenarios will produce different level metadata on loading. Both need to map level iids to their indices and background image handles. External level projects additionally need to produce a handle to the external level asset. This PR provides `LevelMetadata` and `ExternalLevelMetadata` types to represent the metadata produced during project loading.
Mapping iids to level indices with the help of the level metadata types allows constant-time lookup of levels by iid. This is handy since users …
> feat: add types and traits around LevelMetadata

- src/utils.rs
This fixes lints added in clippy 1.73, which have been failing CI.
> chore: address new clippy lints

- .github/workflows/lint.yml
- Cargo.toml
- src/assets/level_indices.rs
- src/assets/level_locale.rs
- src/assets/level_metadata.rs
- src/assets/mod.rs
- src/lib.rs
As part of the rework of the asset types, it is useful to be able to define types that are generic over the "level locale" of the project they represent. The terminology level locale refers to whether or not the project uses internal levels (level data embedded in the main project asset) or external levels (level data stored in separate individual-level files). Such a generic type is able to define different implementations of the same trait for the two locales, or the same implementation of the same trait, or even completely different methods between the two locales.
To facilitate this, this PR adds a `LevelLocale` trait, which is mostly a marker trait implemented by the new `InternalLevels` and `ExternalLevels` unit structs. It does provide an associated type to the sort of level …
> feat: add level locale types and begin splitting internal_levels and external_levels features

- Cargo.toml
- src/assets/level_metadata_accessor.rs
- src/ldtk/fake.rs
- src/ldtk/mod.rs
I would like to have more comprehensive tests, but one obstacle in that respect has always been that the LDtk json types were very difficult to construct for tests. They are quite complicated and massive, so writing custom test data is very time consuming and difficult to maintain. This seems to me like a good use case for a faker library, so that is what this PR implements.
You may notice that these faker types are not very sophisticated, and only edit a few fields. My thoughts are that, as tests need to fake more fields of these types, they are welcome to improve the fakers. The sorts of things that are faked here are those that are used in tests for the new asset types. These fakers are also pretty careful about making the faked data a little bit realistic.. in particular, all faked …
> test: add basic LDtk faker types and use them LevelMetadataAccessor tests

- src/assets/ldtk_project.rs
- src/ldtk/raw_level_accessor.rs
A recent PR added fakers for the LDtk types. `LevelMetadataAccessor` tests were updated to use these faker types, but I mistakenly forgot to add the updates to the `RawLevelAccessor` tests. This PR adds those update, which allows us to delete `RawLevelAccessor::tests::sample_levels`. 
The `LdtkProject` test also is updated for this, even though it won't really be exist in this form for very long.
(Ignore broken doc-links here, they will no longer be broken in future PRs)
> test: use faker types instead of sample_levels helper in RawLevelAccessor and LdtkProject tests

- src/assets/ldtk_json_with_metadata.rs
- src/assets/mod.rs
I have been working on redesigning the asset types to provide more convenient access to level data and a more correct memory model of both internal- and external-level projects. It is useful to represent these two types of projects with similar-but-different rust types, where we can implement some methods/traits as exclusive to each case, and other methods/traits as the same for each case. This is a good use case for generics. This PR adds a generic `LdtkJsonWithMetadata<L>` type for this, which stores just enough information to provide convenient access to loaded level data in either case.
The generic parameter for this type is `L: LevelLocale`, leveraging the `LevelLocale` traits/types added in a previous PR. This parameter will be set to `InternalLevels` for internal-levels projects, …
> feat: add LdtkJsonWithMetadata type for representing internal- and external-level project data with generics

- src/assets/ldtk_project_data.rs
- src/assets/mod.rs
- src/lib.rs
This continues work towards redesigning the asset types. In a previous PR, `LdtkProjectWithMetadata<L>` was added to store LDtk data in a way that it is generic over its level locale. This was done because some methods need to be exclusive to internal-levels projects, some need to be exclusive to external-levels projects, while some need to be the same between the two. However, it is still necessary to represent both cases with the same concrete type (not generic, as that basically treats them as two separate concrete types). This is so we can use these types in bevy's asset system, which doesn't accept multiple asset types being assigned to the same file extension (`.ldtk` in this case).
This PR adds `LdtkProjectData` which is an enum one layer above `LdtkProjectWithMetadata` that has …
> feat: add LdtkProjectData for representing either internal- or external-level project data concretely

- Cargo.toml
- src/assets/ldtk_external_level.rs
- src/assets/ldtk_json_with_metadata.rs
- src/assets/ldtk_project.rs
- src/assets/ldtk_project_data.rs
- src/assets/level_indices.rs
- src/assets/level_locale.rs
- src/assets/level_metadata.rs
- src/assets/level_metadata_accessor.rs
- src/assets/mod.rs
- src/components/mod.rs
- src/ldtk/fake.rs
- src/ldtk/mod.rs
- src/ldtk/raw_level_accessor.rs
- src/systems.rs
Closes #205
This is the final PR for redesigning the asset types. The main improvements of this redesign are that the type provides better APIs for accessing raw or loaded level data, and internal/external levels are modeled more correctly.
The `LdtkProject` type is still the asset type and stores most metadata applicable to either level locale, along with `LdtkProjectData`.
`LdtkProjectData` is a enum whose variants store the actual ldtk json data, with a variant for each level locality. The internal types of the variants are `LdtkJsonWithMetadata<L: LevelLocale>`, with either `InternalLevels` or `ExternalLevels` as `L`.
`LdtkJsonWithMetadata<L>` is a generic type storing the actual ldtk json data + level metadata, with either `InternalLevels` or `ExternalLevels` as `L`.
Splitting these …
> feat!: redesign LdtkProject with better level data accessors and correct modeling of internal/external levels

- Cargo.toml
Closes #246 
Now that entire types are being hidden behind features, it's important that we enable this option so that they are visible in doc.rs. I also looked into enabling other common features like `--generate-link-to-definition`, but this seems to be only relevant if we're publishing the docs ourselves instead of relying on docs.rs, so I left that out for now.
> docs: document all-features in docs.rs

- README.md
Related to #1 
Since bevy's file changewatcher now accepts a `Duration`, running into the bug caused by level files being temporarily unavailable is either extremely unlikely or impossible with a reasonable duration. So, I think it's safe to remove this caveat from the readme saying that users need to double-save for hot-reloading to work for external levels.
> docs: remove README.md caveat for hot reloading external levels

- Cargo.toml
- src/assets/ldtk_project.rs
Makes all paths relative to the `assets` root. Ensures that LDtk-linked assets are shared with assets loaded by `AssetServer`, [bevy_asset_loader](https://github.com/NiklasEi/bevy_asset_loader) and so on, as long as normalized paths are used for those (as they typically are), especially when the LDtk project is in a subdirectory.
Fixes #240
> Normalize resolved asset paths using `path_clean`.

- src/level.rs
Closes #248 
Currently, we adjust the adjust the transform of layer entities to account for the following:
- bevy_ecs_tilemap anchoring tiles to their center (we need to cancel this out to make all layers of different sizes stack on top of each other nicely)
- layer offset values
However, for more niche cases of using a layer grid size that differs from the tileset tile size, this isn't sufficient. We also need to adjust the layer's transform to account for the following:
- the difference between the layer size and grid size causing tiles to sink below the origin with default pivot
- tiles having an in-LDtk pivot (anchor) value (which makes no difference when tile size = grid size)
This PR makes these additional adjustments. It also makes some stylistic changes that I hope will make some …
> fix: recalculate layer offset to adjust for tileset sizes

- src/components/mod.rs
- src/level.rs
- src/lib.rs
- src/plugin.rs
- src/systems.rs
- src/utils.rs
Closes #224 
Ever since layer metadata has been accessible for tile-based layer entities via a component, it has become a pain point that entity layers do not have a layer entity associated with them. This PR makes it so they do. Now, `LdtkEntity`/`EntityInstance`s spawned by the plugin will be children of a layer entity w/ a `LayerMetadata` component, which in turn is a child of the level entity. The behavior of the `Worldly` component has been adjusted accordingly.
The scheduling of `worldly_adoption` has also changed. In the most recent iteration of the schedule, the main constraint for scheduling this system was that it should be after `Update` to have minimal frame delay in the odd case that a user adds it to entities manually in `Update`. Putting it in `PostUpdate` still satisfies …
> feat!: add layer entity for Entity layers, changing the hierarchy

- .github/workflows/release-please.yml
#261 added extra config to the release-please CI to format an extra file w/ the version number. However, the formatting of this config argument was wrong. This PR should fix it.
> ci: fix formatting of extra-files option for release-please

- .github/workflows/lint.yml
- .github/workflows/publish-book.yml
- .github/workflows/release-please.yml
Now that we have a book as part of our documentation, new builds of this book should be published for new versions of the plugin, similar to docs.rs. This PR accomplishes this by adding a workflow to the CI that publishes the book to github pages on new releases. Furthermore, the token used by release-please has been updated so that it can trigger workflows itself (something the default `secrets.GH_TOKEN` is not capable of).
The workflow has been tested, and a preview of the book is now available: https://trouv.github.io/bevy_ecs_ldtk
> ci: publish book to github pages on new releases

- book/src/SUMMARY.md
- book/src/how-to-guides/migration-guides/README.md
- book/src/how-to-guides/migration-guides/migrate-from-0.8-to-0.9.md
`bevy_ecs_ldtk` 0.9 has many more breaking changes than any other release so far. I think it would be nice to provide users with a migration guide, which will document most of the changes they will need to make in their games to continue using the plugin. The changes I've chosen to describe here are basically anything that's labeled as a breaking change in the changelog. I verified that the repo examples between now and `0.8` haven't had to deal with any other breaking change, so this should be complete (especially under normal usage).
Note that this does *not* contain a section about updating to 0.12. I will add that to the 0.12 upgrade PR after this is merged.
Furthermore, the 0.9 doc-tests here are generally marked as `no_run`, not `ignore`. These should be changed back to `ignore` …
> docs: add 0.8 to 0.9 migration guide

- src/utils.rs
Closes #267 
LDtk populates an `EntityInstance`'s `__tile` field if any tile is used when visualizing that entity in-level. This is normally just the entity's editor visual, but if that entity is given a singular tile field instance and has no editor visual, it might use that instead. Currently, `bevy_ecs_ldtk` uses this field to calculate the scale when spawning `EntityInstance`s. This can lead to unexpected behavior. The scale of entity instances with no entity visual should correlate to the size of the instance in the level. This might not be the case for entities that have a tile field despite having no editor visual. The solution implemented here is to use the `tileRect` field of the entity definition instead of the `__tile` field of the entity instance.
To be honest, I'm not totally …
> fix: use entity definition tile size instead of entity instance tile size as basis when calculating ldtk entity scale

- src/level.rs
- src/lib.rs
- src/resources/mod.rs
I made this a separate `LdtkExclusions` struct because, even though there's only one use case for this now, it would be a logical extension to add other exclusions in the future (like entities, both IID and UID based), and if so, it's better to group them together instead of cluttering up the main `LdtkSettings`.
Caveat: Adding a `Vec` (or any other collection) to the `LdtkSettings` or any sub-structure means we can no longer derive `Copy`. It doesn't appear to be required by any part of `bevy_ecs_ldtk` itself, and there's no compelling reason why users should absolutely need it (copying a `Resource` is pretty rare?), but this is potentially a breaking change for some users. The only way around this would be to avoid putting this in `LdtkSettings` altogether and define the …
> Add exclusions to `LdtkSettings` and filters to level spawner.

- book/src/README.md
- book/src/SUMMARY.md
- book/src/explanation/game-logic-integration.md
This chapter covers the main strategies for integrating game logic with LDtk projects, and also compares them. These main strategies being `LdtkEntity`/`LdtkIntCell` registration and the blueprint pattern. In a future PR, explanations of these concepts in the API reference and project readme will be removed in favor of linking to this chapter.
> docs: write *Game Logic Integration* chapter of the book

- .github/workflows/publish-book.yml
- examples/tile_based_game.rs
Closes #274 
This changes the publish book CI to subdirectories of the github pages branch rather than the root. The directory name is either the tag name that triggered the publishing, or the branch name (which can only be `main` due to the workflow triggers). Furthermore, if it is a tag that triggered the publishing, the `latest` directory is *also* published to. So the result will be multiple versions of the book published to github pages, one for each version of the plugin named after that version, plus two special versions: `latest` and `main`. This will help with development of the book and allow users of older versions of the plugin to reference older documentation.
> ci: publish book to versioned subdirectories

- .github/workflows/release-please.yml
- README.md
- book/src/README.md
- book/src/SUMMARY.md
- book/src/explanation/level-selection.md
- examples/level_set.rs
- src/components/level_set.rs
- src/lib.rs
- src/resources/level_selection.rs
- src/resources/mod.rs
This new chapter explains and compares the strategies for spawning levels:
- `LevelSelection`
- `LevelSet`
- `load_level_neighbors`...
In writing this, I realized this was actually a better first explanation chapter for the book than *Game Logic Integration*, so I've placed it first and also referenced it directly in `README.md`, `src/lib.rs`, and the book introduction.
Any explanations in the API reference made redundant by this chapter have been updated to reference the chapter instead.
> docs: write *Level Selection* chapter of book

- .github/workflows/release-please.yml
- book/src/SUMMARY.md
- book/src/explanation/anatomy-of-the-world.md
- book/src/explanation/hierarchy-of-the-world.md
- src/app/ldtk_entity.rs
- src/components/mod.rs
- src/lib.rs
This new chapter explains in greater detail the results of spawning the world/levels. This includes the explanation of the hierarchy, worldly entities, tile metadata, level backgrounds, layers with colliding tiles, and z ordering.
Redundant explanations in the API reference have been replaced by references to this chapter.
> docs: write *Anatomy of the World* chapter of book

- book/src/SUMMARY.md
- book/src/how-to-guides/create-bevy-relations-from-ldtk-entity-references.md
This adds a simple how-to-guide for creating bevy relations from LDtk entity references. This has already been kind-of documented by the field_instances example, which this chapter uses code from heavily.
> docs: write *Create bevy relations from ldtk entity references* chapter of book

- .github/workflows/release-please.yml
- book/src/SUMMARY.md
- book/src/how-to-guides/respawn-levels-and-worlds.md
- src/components/mod.rs
This chapter demonstrates usage of the `Respawn` component. It uses code from the new `collectathon` cargo example. This makes some docs in the api reference redundant, so those have been replaced with a link to the book.
> docs: write *Respawn levels and worlds* chapter of book

- book/src/SUMMARY.md
- book/src/how-to-guides/make-level-selection-follow-player.md
- examples/collectathon/player.rs
This demonstrates how to update the `LevelSelection` based on the level the player is currently in, for games that use `LevelSpawnBehavior::UseWorldTranslation` and a `Worldly` player. It uses code from the new `collectathon` example (and improves that code a little bit).
> docs: write *Make level selection follow player* chapter of book

- Cargo.toml
- README.md
- book/src/how-to-guides/respawn-levels-and-worlds.md
- examples/collectathon/player.rs
- examples/collectathon/respawn.rs
- examples/level_set.rs
- examples/platformer/components.rs
- examples/platformer/systems.rs
- examples/tile_based_game.rs
- examples/traitless.rs
- macros/src/ldtk_entity.rs
- src/app/entity_app_ext.rs
- src/app/ldtk_entity.rs
- src/app/ldtk_int_cell.rs
- src/ldtk/impl_definitions.rs
- src/level.rs
- src/systems.rs
- src/utils.rs
~~Leaving this in draft until https://github.com/StarArawn/bevy_ecs_tilemap/pull/508 merges.~~
Upstream `bevy_ecs_tilemap` PR has merged, but a new release hasn't been cut. PR updated to note that `main` here tracks to `main` for ECS Tilemap which both allow for Bevy 0.13 support and PR should be mergeable.
Most of the changes here are related to the new `TextureAtlasLayout` and the examples in the repo look correct to me still at least.
Fixes #301
> Bevy 0.13 support

- book/src/explanation/game-logic-integration.md
This param wasn't being "used" in this example code.
> Remove unused asset server param

- Cargo.toml
- README.md
- examples/field_instances/level_title.rs
Closes #321
Currently, we're using a patch to depend on `bevy_ecs_tilemap`.  This places a burden on the user to use a similar patch in their own `Cargo.toml`. We're also using the `main` branch of `bevy_ecs_tilemap` in this patch. This can lead to issues when updates occur to that branch of the `bevy_ecs_tilemap` repository, as new users and `cargo update`rs will pull in any new changes to that repo, even breaking ones. This is currently affecting our CI.
This PR's changes will ultimately be overwritten soon by an update to bevy 0.14 (#325), but merging this sooner will help set the standard for development of this project inbetween `bevy_ecs_tilemap` releases in the future, and also unblock other PRs whose CI checks are affected (#306).
> build: use a git revision dependency for bevy_ecs_tilemap instead of a git branch patch

- macros/src/ldtk_entity.rs
- macros/src/ldtk_int_cell.rs
- macros/src/lib.rs
- src/app/ldtk_entity.rs
- src/app/ldtk_int_cell.rs
Add an attribute that initializes fields using individual field Default implementations, allowing to use the derive macros again without requiring the whole struct to implement Default (when some fields should be default-initialized and others use initialization attributes like #[from_entity_instance]).
Fixes #305
> feat: add #[default] attribute to LdtkEntity and LdtkIntCell derive macros

- examples/field_instances/main.rs
- src/app/ldtk_entity.rs
- src/ldtk/mod.rs
Rust 1.80 has been released, and new clippy lints are now being checked in our CI. This PR addresses these lints to uphold the code quality of this repository and get the clippy CI job passing again.
The new lint that was failing is `doc_lazy_continuation`, so this PR only really affects docs. This lint was simply `#[allow(...)]`'d in the `ldtk` module since most of the code in this module is auto-generated and any manual changes to it need to be repeated whenever it is regenerated.
> ci: address new clippy lints in 1.80

- README.md
This updates the compatibility chart in the README.md in anticipation of the release of bevy_ecs_ldtk 0.11.
> chore: add bevy_ecs_ldtk 0.11 to compatibility chart

- README.md
In prepraration for the 0.12 release, we need to document what versions of bevy, bevy_ecs_tilemap, and LDtk are supported in the compatibility chart.
> chore: add bevy_ecs_ldtk 0.12 to compatibility chart
